import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "@/app/styles/globals.scss";
import Nav from "./components/nav.component";
import {Providers} from "@/app/providers";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({
                        children,
                    }: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="en">

        <body className={inter.className}>
        <Nav/>
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    );
}

export default RootLayout;
