import React, { type ReactElement } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/globals.scss';
import Nav from '@/lib/components/nav.component';
import { Providers } from '@/app/providers';
import { UserProvider } from '@auth0/nextjs-auth0/client';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>): ReactElement => {
  return (
        <html lang="en">
        <UserProvider>
            <body className={inter.className}>
            <Nav/>
            <Providers>
                {children}
            </Providers>
            </body>
        </UserProvider>
        </html>
  );
};

export default RootLayout;
