import React, { type ReactElement } from 'react';
import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import '@/app/globals.css';
import Nav from '@/lib/components/nav/nav.component';
import { Providers } from '@/app/providers';
import { type LangParams } from '@/lib/models/dictionaries/lang-params';
import '@/lib/styles/animations/gsap-config';
import Footer from '@/lib/components/footer/footer.component';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from "@vercel/analytics/react";
import { GeistSans } from 'geist/font/sans';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface RootLayoutProps {
  params: LangParams | Promise<LangParams>;
  children: React.ReactNode;
}

const RootLayout = async (
  { params, children }: Readonly<RootLayoutProps>): Promise<ReactElement> => {

  const awaitedParams = await params;
  const { lang } = awaitedParams;

  return (
    <html lang={ lang }>
      <body className={GeistSans.className}>
        <Providers>
          <Nav params={{ lang }} />
          {children}
          <Footer params={{ lang }} />
          <SpeedInsights />
          <Analytics />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
